[package]
name = "sharex-rs"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1", features = ["full"] }
dotenv = "0.15.0"
anyhow = "1.0.70"
log = "0.4.17"
simple_logger = "4.1.0"
axum = { version = "0.6.12", features = ["multipart"] }
rand = "0.8.5"
mime_guess = "2.0.4"
